# Generated by Django 3.1.7 on 2021-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.DecimalField(decimal_places=0, default=361, max_digits=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.DecimalField(decimal_places=0, default=11, max_digits=3),
        ),
    ]
