# Generated by Django 3.1.7 on 2021-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210330_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.DecimalField(decimal_places=0, default=4138, max_digits=4),
        ),
    ]
