# Generated by Django 3.1.7 on 2021-03-29 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
