# Generated by Django 3.1.7 on 2021-03-29 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210329_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 23, 55, 44, 333755)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.DecimalField(decimal_places=1, default=31752, max_digits=6),
        ),
    ]
