# Generated by Django 3.1.7 on 2021-03-29 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210329_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 23, 57, 47, 293274)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.DecimalField(decimal_places=0, default=24295, max_digits=6),
        ),
    ]
