# Generated by Django 3.1.7 on 2021-03-29 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210329_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 0, 0, 38, 873867)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.DecimalField(decimal_places=0, default=20686, max_digits=6),
        ),
    ]
